/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface FallbackManagerInterface extends ethers.utils.Interface {
  functions: {
    "getFallbackHandler()": FunctionFragment;
    "setFallbackHandler(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getFallbackHandler",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFallbackHandler",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getFallbackHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFallbackHandler",
    data: BytesLike
  ): Result;

  events: {
    "ChangedFallbackHandler(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChangedFallbackHandler"): EventFragment;
}

export class FallbackManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: FallbackManagerInterface;

  functions: {
    getFallbackHandler(overrides?: CallOverrides): Promise<{
      _handler: string;
      0: string;
    }>;

    "getFallbackHandler()"(overrides?: CallOverrides): Promise<{
      _handler: string;
      0: string;
    }>;

    setFallbackHandler(
      handler: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setFallbackHandler(address)"(
      handler: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getFallbackHandler(overrides?: CallOverrides): Promise<string>;

  "getFallbackHandler()"(overrides?: CallOverrides): Promise<string>;

  setFallbackHandler(
    handler: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setFallbackHandler(address)"(
    handler: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getFallbackHandler(overrides?: CallOverrides): Promise<string>;

    "getFallbackHandler()"(overrides?: CallOverrides): Promise<string>;

    setFallbackHandler(
      handler: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setFallbackHandler(address)"(
      handler: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    ChangedFallbackHandler(
      previousHandler: string | null,
      handler: string | null
    ): EventFilter;
  };

  estimateGas: {
    getFallbackHandler(overrides?: CallOverrides): Promise<BigNumber>;

    "getFallbackHandler()"(overrides?: CallOverrides): Promise<BigNumber>;

    setFallbackHandler(
      handler: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setFallbackHandler(address)"(
      handler: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getFallbackHandler(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getFallbackHandler()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFallbackHandler(
      handler: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setFallbackHandler(address)"(
      handler: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
