/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface INonceManagerInterface extends ethers.utils.Interface {
  functions: {
    "getNonce(address,uint192)": FunctionFragment;
    "incrementNonce(uint192)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getNonce",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementNonce",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "incrementNonce",
    data: BytesLike
  ): Result;

  events: {};
}

export class INonceManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: INonceManagerInterface;

  functions: {
    getNonce(
      sender: string,
      key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      nonce: BigNumber;
      0: BigNumber;
    }>;

    "getNonce(address,uint192)"(
      sender: string,
      key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      nonce: BigNumber;
      0: BigNumber;
    }>;

    incrementNonce(
      key: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "incrementNonce(uint192)"(
      key: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getNonce(
    sender: string,
    key: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getNonce(address,uint192)"(
    sender: string,
    key: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  incrementNonce(
    key: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "incrementNonce(uint192)"(
    key: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getNonce(
      sender: string,
      key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNonce(address,uint192)"(
      sender: string,
      key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    incrementNonce(key: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "incrementNonce(uint192)"(
      key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getNonce(
      sender: string,
      key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNonce(address,uint192)"(
      sender: string,
      key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    incrementNonce(
      key: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "incrementNonce(uint192)"(
      key: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getNonce(
      sender: string,
      key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNonce(address,uint192)"(
      sender: string,
      key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    incrementNonce(
      key: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "incrementNonce(uint192)"(
      key: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
