/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SenderCreatorInterface extends ethers.utils.Interface {
  functions: {
    "createSender(bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createSender",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSender",
    data: BytesLike
  ): Result;

  events: {};
}

export class SenderCreator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SenderCreatorInterface;

  functions: {
    createSender(
      initCode: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createSender(bytes)"(
      initCode: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  createSender(
    initCode: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createSender(bytes)"(
    initCode: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    createSender(
      initCode: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "createSender(bytes)"(
      initCode: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createSender(
      initCode: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createSender(bytes)"(
      initCode: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createSender(
      initCode: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createSender(bytes)"(
      initCode: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
