/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SmartAccountInterface extends ethers.utils.Interface {
  functions: {
    "addDeposit()": FunctionFragment;
    "addHook(address,bytes)": FunctionFragment;
    "addRecoveror(address,bytes)": FunctionFragment;
    "disableValidator(address,address)": FunctionFragment;
    "enableValidator(address,bytes)": FunctionFragment;
    "entryPoint()": FunctionFragment;
    "execute(address,uint256,bytes)": FunctionFragment;
    "executeBatch(address[],uint256[],bytes[])": FunctionFragment;
    "getDeposit()": FunctionFragment;
    "getFallbackHandler()": FunctionFragment;
    "getNonce()": FunctionFragment;
    "getRecoverorsPaginated(address,uint256)": FunctionFragment;
    "getValidatorsPaginated(address,uint256)": FunctionFragment;
    "initialize(address,address[],bytes[])": FunctionFragment;
    "isRecoverorEnabled(address)": FunctionFragment;
    "isValidatorEnabled(address)": FunctionFragment;
    "recovery(address,bytes)": FunctionFragment;
    "removeRecoveror(address,address,address)": FunctionFragment;
    "setFallbackHandler(address)": FunctionFragment;
    "sudo(address,uint256,bytes)": FunctionFragment;
    "validateUserOp(tuple,bytes32,uint256)": FunctionFragment;
    "withdrawDepositTo(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addHook",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addRecoveror",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disableValidator",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "enableValidator",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [string[], BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFallbackHandler",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getNonce", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRecoverorsPaginated",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorsPaginated",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isRecoverorEnabled",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidatorEnabled",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "recovery",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRecoveror",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFallbackHandler",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "sudo",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateUserOp",
    values: [
      {
        sender: string;
        nonce: BigNumberish;
        initCode: BytesLike;
        callData: BytesLike;
        callGasLimit: BigNumberish;
        verificationGasLimit: BigNumberish;
        preVerificationGas: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymasterAndData: BytesLike;
        signature: BytesLike;
      },
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawDepositTo",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addHook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addRecoveror",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFallbackHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecoverorsPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorsPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRecoverorEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidatorEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recovery", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeRecoveror",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFallbackHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sudo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateUserOp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDepositTo",
    data: BytesLike
  ): Result;

  events: {
    "AddedRecoveror(address)": EventFragment;
    "ChangedFallbackHandler(address,address)": EventFragment;
    "DisabledValidator(address)": EventFragment;
    "EnabledValidator(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "InstalledHook(address)": EventFragment;
    "RemovedRecoveror(address)": EventFragment;
    "UninstalledHook(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddedRecoveror"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChangedFallbackHandler"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DisabledValidator"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EnabledValidator"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InstalledHook"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemovedRecoveror"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UninstalledHook"): EventFragment;
}

export class SmartAccount extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SmartAccountInterface;

  functions: {
    addDeposit(overrides?: PayableOverrides): Promise<ContractTransaction>;

    "addDeposit()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

    addHook(
      hook: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addHook(address,bytes)"(
      hook: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addRecoveror(
      recoveror: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addRecoveror(address,bytes)"(
      recoveror: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    disableValidator(
      prevValidator: string,
      validator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "disableValidator(address,address)"(
      prevValidator: string,
      validator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    enableValidator(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "enableValidator(address,bytes)"(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    entryPoint(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "entryPoint()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    execute(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "execute(address,uint256,bytes)"(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    executeBatch(
      dest: string[],
      value: BigNumberish[],
      func: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeBatch(address[],uint256[],bytes[])"(
      dest: string[],
      value: BigNumberish[],
      func: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getDeposit(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "getDeposit()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    getFallbackHandler(overrides?: CallOverrides): Promise<{
      _handler: string;
      0: string;
    }>;

    "getFallbackHandler()"(overrides?: CallOverrides): Promise<{
      _handler: string;
      0: string;
    }>;

    getNonce(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "getNonce()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    getRecoverorsPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      array: string[];
      next: string;
      0: string[];
      1: string;
    }>;

    "getRecoverorsPaginated(address,uint256)"(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      array: string[];
      next: string;
      0: string[];
      1: string;
    }>;

    getValidatorsPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      array: string[];
      next: string;
      0: string[];
      1: string;
    }>;

    "getValidatorsPaginated(address,uint256)"(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      array: string[];
      next: string;
      0: string[];
      1: string;
    }>;

    initialize(
      defalutCallbackHandler: string,
      validators: string[],
      data: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address[],bytes[])"(
      defalutCallbackHandler: string,
      validators: string[],
      data: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isRecoverorEnabled(
      recoveror: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isRecoverorEnabled(address)"(
      recoveror: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    isValidatorEnabled(
      validator: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isValidatorEnabled(address)"(
      validator: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    recovery(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "recovery(address,bytes)"(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeRecoveror(address,address,address)"(
      prevBeforeHook: string,
      prevAfterHook: string,
      hook: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeRecoveror(address,address)"(
      prevRecoveror: string,
      recoveror: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setFallbackHandler(
      handler: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setFallbackHandler(address)"(
      handler: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sudo(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sudo(address,uint256,bytes)"(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    validateUserOp(
      userOp: {
        sender: string;
        nonce: BigNumberish;
        initCode: BytesLike;
        callData: BytesLike;
        callGasLimit: BigNumberish;
        verificationGasLimit: BigNumberish;
        preVerificationGas: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymasterAndData: BytesLike;
        signature: BytesLike;
      },
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "validateUserOp(tuple,bytes32,uint256)"(
      userOp: {
        sender: string;
        nonce: BigNumberish;
        initCode: BytesLike;
        callData: BytesLike;
        callGasLimit: BigNumberish;
        verificationGasLimit: BigNumberish;
        preVerificationGas: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymasterAndData: BytesLike;
        signature: BytesLike;
      },
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawDepositTo(
      withdrawAddress: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawDepositTo(address,uint256)"(
      withdrawAddress: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  addDeposit(overrides?: PayableOverrides): Promise<ContractTransaction>;

  "addDeposit()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

  addHook(
    hook: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addHook(address,bytes)"(
    hook: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addRecoveror(
    recoveror: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addRecoveror(address,bytes)"(
    recoveror: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  disableValidator(
    prevValidator: string,
    validator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "disableValidator(address,address)"(
    prevValidator: string,
    validator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  enableValidator(
    validator: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "enableValidator(address,bytes)"(
    validator: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  entryPoint(overrides?: CallOverrides): Promise<string>;

  "entryPoint()"(overrides?: CallOverrides): Promise<string>;

  execute(
    dest: string,
    value: BigNumberish,
    func: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "execute(address,uint256,bytes)"(
    dest: string,
    value: BigNumberish,
    func: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  executeBatch(
    dest: string[],
    value: BigNumberish[],
    func: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeBatch(address[],uint256[],bytes[])"(
    dest: string[],
    value: BigNumberish[],
    func: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getDeposit(overrides?: CallOverrides): Promise<BigNumber>;

  "getDeposit()"(overrides?: CallOverrides): Promise<BigNumber>;

  getFallbackHandler(overrides?: CallOverrides): Promise<string>;

  "getFallbackHandler()"(overrides?: CallOverrides): Promise<string>;

  getNonce(overrides?: CallOverrides): Promise<BigNumber>;

  "getNonce()"(overrides?: CallOverrides): Promise<BigNumber>;

  getRecoverorsPaginated(
    start: string,
    pageSize: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    array: string[];
    next: string;
    0: string[];
    1: string;
  }>;

  "getRecoverorsPaginated(address,uint256)"(
    start: string,
    pageSize: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    array: string[];
    next: string;
    0: string[];
    1: string;
  }>;

  getValidatorsPaginated(
    start: string,
    pageSize: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    array: string[];
    next: string;
    0: string[];
    1: string;
  }>;

  "getValidatorsPaginated(address,uint256)"(
    start: string,
    pageSize: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    array: string[];
    next: string;
    0: string[];
    1: string;
  }>;

  initialize(
    defalutCallbackHandler: string,
    validators: string[],
    data: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address[],bytes[])"(
    defalutCallbackHandler: string,
    validators: string[],
    data: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isRecoverorEnabled(
    recoveror: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isRecoverorEnabled(address)"(
    recoveror: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isValidatorEnabled(
    validator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isValidatorEnabled(address)"(
    validator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  recovery(
    validator: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "recovery(address,bytes)"(
    validator: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeRecoveror(address,address,address)"(
    prevBeforeHook: string,
    prevAfterHook: string,
    hook: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeRecoveror(address,address)"(
    prevRecoveror: string,
    recoveror: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setFallbackHandler(
    handler: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setFallbackHandler(address)"(
    handler: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sudo(
    dest: string,
    value: BigNumberish,
    func: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sudo(address,uint256,bytes)"(
    dest: string,
    value: BigNumberish,
    func: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  validateUserOp(
    userOp: {
      sender: string;
      nonce: BigNumberish;
      initCode: BytesLike;
      callData: BytesLike;
      callGasLimit: BigNumberish;
      verificationGasLimit: BigNumberish;
      preVerificationGas: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymasterAndData: BytesLike;
      signature: BytesLike;
    },
    userOpHash: BytesLike,
    missingAccountFunds: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "validateUserOp(tuple,bytes32,uint256)"(
    userOp: {
      sender: string;
      nonce: BigNumberish;
      initCode: BytesLike;
      callData: BytesLike;
      callGasLimit: BigNumberish;
      verificationGasLimit: BigNumberish;
      preVerificationGas: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymasterAndData: BytesLike;
      signature: BytesLike;
    },
    userOpHash: BytesLike,
    missingAccountFunds: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawDepositTo(
    withdrawAddress: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawDepositTo(address,uint256)"(
    withdrawAddress: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    addDeposit(overrides?: CallOverrides): Promise<void>;

    "addDeposit()"(overrides?: CallOverrides): Promise<void>;

    addHook(
      hook: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "addHook(address,bytes)"(
      hook: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    addRecoveror(
      recoveror: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "addRecoveror(address,bytes)"(
      recoveror: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    disableValidator(
      prevValidator: string,
      validator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "disableValidator(address,address)"(
      prevValidator: string,
      validator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    enableValidator(
      validator: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "enableValidator(address,bytes)"(
      validator: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    entryPoint(overrides?: CallOverrides): Promise<string>;

    "entryPoint()"(overrides?: CallOverrides): Promise<string>;

    execute(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "execute(address,uint256,bytes)"(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    executeBatch(
      dest: string[],
      value: BigNumberish[],
      func: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "executeBatch(address[],uint256[],bytes[])"(
      dest: string[],
      value: BigNumberish[],
      func: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    getDeposit(overrides?: CallOverrides): Promise<BigNumber>;

    "getDeposit()"(overrides?: CallOverrides): Promise<BigNumber>;

    getFallbackHandler(overrides?: CallOverrides): Promise<string>;

    "getFallbackHandler()"(overrides?: CallOverrides): Promise<string>;

    getNonce(overrides?: CallOverrides): Promise<BigNumber>;

    "getNonce()"(overrides?: CallOverrides): Promise<BigNumber>;

    getRecoverorsPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      array: string[];
      next: string;
      0: string[];
      1: string;
    }>;

    "getRecoverorsPaginated(address,uint256)"(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      array: string[];
      next: string;
      0: string[];
      1: string;
    }>;

    getValidatorsPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      array: string[];
      next: string;
      0: string[];
      1: string;
    }>;

    "getValidatorsPaginated(address,uint256)"(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      array: string[];
      next: string;
      0: string[];
      1: string;
    }>;

    initialize(
      defalutCallbackHandler: string,
      validators: string[],
      data: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address[],bytes[])"(
      defalutCallbackHandler: string,
      validators: string[],
      data: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    isRecoverorEnabled(
      recoveror: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isRecoverorEnabled(address)"(
      recoveror: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isValidatorEnabled(
      validator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isValidatorEnabled(address)"(
      validator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    recovery(
      validator: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "recovery(address,bytes)"(
      validator: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeRecoveror(address,address,address)"(
      prevBeforeHook: string,
      prevAfterHook: string,
      hook: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeRecoveror(address,address)"(
      prevRecoveror: string,
      recoveror: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setFallbackHandler(
      handler: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setFallbackHandler(address)"(
      handler: string,
      overrides?: CallOverrides
    ): Promise<void>;

    sudo(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "sudo(address,uint256,bytes)"(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    validateUserOp(
      userOp: {
        sender: string;
        nonce: BigNumberish;
        initCode: BytesLike;
        callData: BytesLike;
        callGasLimit: BigNumberish;
        verificationGasLimit: BigNumberish;
        preVerificationGas: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymasterAndData: BytesLike;
        signature: BytesLike;
      },
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "validateUserOp(tuple,bytes32,uint256)"(
      userOp: {
        sender: string;
        nonce: BigNumberish;
        initCode: BytesLike;
        callData: BytesLike;
        callGasLimit: BigNumberish;
        verificationGasLimit: BigNumberish;
        preVerificationGas: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymasterAndData: BytesLike;
        signature: BytesLike;
      },
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawDepositTo(
      withdrawAddress: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawDepositTo(address,uint256)"(
      withdrawAddress: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AddedRecoveror(recoveror: null): EventFilter;

    ChangedFallbackHandler(
      previousHandler: string | null,
      handler: string | null
    ): EventFilter;

    DisabledValidator(validator: null): EventFilter;

    EnabledValidator(validator: null): EventFilter;

    Initialized(version: null): EventFilter;

    InstalledHook(hook: string | null): EventFilter;

    RemovedRecoveror(recoveror: null): EventFilter;

    UninstalledHook(hook: string | null): EventFilter;
  };

  estimateGas: {
    addDeposit(overrides?: PayableOverrides): Promise<BigNumber>;

    "addDeposit()"(overrides?: PayableOverrides): Promise<BigNumber>;

    addHook(
      hook: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addHook(address,bytes)"(
      hook: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addRecoveror(
      recoveror: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addRecoveror(address,bytes)"(
      recoveror: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    disableValidator(
      prevValidator: string,
      validator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "disableValidator(address,address)"(
      prevValidator: string,
      validator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    enableValidator(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "enableValidator(address,bytes)"(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    entryPoint(overrides?: CallOverrides): Promise<BigNumber>;

    "entryPoint()"(overrides?: CallOverrides): Promise<BigNumber>;

    execute(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "execute(address,uint256,bytes)"(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    executeBatch(
      dest: string[],
      value: BigNumberish[],
      func: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeBatch(address[],uint256[],bytes[])"(
      dest: string[],
      value: BigNumberish[],
      func: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    getDeposit(overrides?: CallOverrides): Promise<BigNumber>;

    "getDeposit()"(overrides?: CallOverrides): Promise<BigNumber>;

    getFallbackHandler(overrides?: CallOverrides): Promise<BigNumber>;

    "getFallbackHandler()"(overrides?: CallOverrides): Promise<BigNumber>;

    getNonce(overrides?: CallOverrides): Promise<BigNumber>;

    "getNonce()"(overrides?: CallOverrides): Promise<BigNumber>;

    getRecoverorsPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRecoverorsPaginated(address,uint256)"(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getValidatorsPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getValidatorsPaginated(address,uint256)"(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      defalutCallbackHandler: string,
      validators: string[],
      data: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address[],bytes[])"(
      defalutCallbackHandler: string,
      validators: string[],
      data: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    isRecoverorEnabled(
      recoveror: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isRecoverorEnabled(address)"(
      recoveror: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidatorEnabled(
      validator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isValidatorEnabled(address)"(
      validator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recovery(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "recovery(address,bytes)"(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeRecoveror(address,address,address)"(
      prevBeforeHook: string,
      prevAfterHook: string,
      hook: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeRecoveror(address,address)"(
      prevRecoveror: string,
      recoveror: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setFallbackHandler(
      handler: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setFallbackHandler(address)"(
      handler: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sudo(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sudo(address,uint256,bytes)"(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    validateUserOp(
      userOp: {
        sender: string;
        nonce: BigNumberish;
        initCode: BytesLike;
        callData: BytesLike;
        callGasLimit: BigNumberish;
        verificationGasLimit: BigNumberish;
        preVerificationGas: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymasterAndData: BytesLike;
        signature: BytesLike;
      },
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "validateUserOp(tuple,bytes32,uint256)"(
      userOp: {
        sender: string;
        nonce: BigNumberish;
        initCode: BytesLike;
        callData: BytesLike;
        callGasLimit: BigNumberish;
        verificationGasLimit: BigNumberish;
        preVerificationGas: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymasterAndData: BytesLike;
        signature: BytesLike;
      },
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawDepositTo(
      withdrawAddress: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawDepositTo(address,uint256)"(
      withdrawAddress: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addDeposit(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    "addDeposit()"(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    addHook(
      hook: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addHook(address,bytes)"(
      hook: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addRecoveror(
      recoveror: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addRecoveror(address,bytes)"(
      recoveror: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    disableValidator(
      prevValidator: string,
      validator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "disableValidator(address,address)"(
      prevValidator: string,
      validator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    enableValidator(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "enableValidator(address,bytes)"(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    entryPoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "entryPoint()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    execute(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "execute(address,uint256,bytes)"(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    executeBatch(
      dest: string[],
      value: BigNumberish[],
      func: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeBatch(address[],uint256[],bytes[])"(
      dest: string[],
      value: BigNumberish[],
      func: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getDeposit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getDeposit()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFallbackHandler(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getFallbackHandler()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNonce(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getNonce()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRecoverorsPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRecoverorsPaginated(address,uint256)"(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getValidatorsPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getValidatorsPaginated(address,uint256)"(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      defalutCallbackHandler: string,
      validators: string[],
      data: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address[],bytes[])"(
      defalutCallbackHandler: string,
      validators: string[],
      data: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isRecoverorEnabled(
      recoveror: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isRecoverorEnabled(address)"(
      recoveror: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidatorEnabled(
      validator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isValidatorEnabled(address)"(
      validator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recovery(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "recovery(address,bytes)"(
      validator: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeRecoveror(address,address,address)"(
      prevBeforeHook: string,
      prevAfterHook: string,
      hook: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeRecoveror(address,address)"(
      prevRecoveror: string,
      recoveror: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setFallbackHandler(
      handler: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setFallbackHandler(address)"(
      handler: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sudo(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sudo(address,uint256,bytes)"(
      dest: string,
      value: BigNumberish,
      func: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    validateUserOp(
      userOp: {
        sender: string;
        nonce: BigNumberish;
        initCode: BytesLike;
        callData: BytesLike;
        callGasLimit: BigNumberish;
        verificationGasLimit: BigNumberish;
        preVerificationGas: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymasterAndData: BytesLike;
        signature: BytesLike;
      },
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "validateUserOp(tuple,bytes32,uint256)"(
      userOp: {
        sender: string;
        nonce: BigNumberish;
        initCode: BytesLike;
        callData: BytesLike;
        callGasLimit: BigNumberish;
        verificationGasLimit: BigNumberish;
        preVerificationGas: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymasterAndData: BytesLike;
        signature: BytesLike;
      },
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawDepositTo(
      withdrawAddress: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawDepositTo(address,uint256)"(
      withdrawAddress: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
