/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface Secp256r1IoTeXInterface extends utils.Interface {
  functions: {
    "validateSignature(bytes32,bytes,bytes)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "validateSignature"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "validateSignature",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "validateSignature",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Secp256r1IoTeX extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Secp256r1IoTeXInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    validateSignature(
      message: BytesLike,
      signature: BytesLike,
      publicKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean] & { result: boolean }>;
  };

  validateSignature(
    message: BytesLike,
    signature: BytesLike,
    publicKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    validateSignature(
      message: BytesLike,
      signature: BytesLike,
      publicKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    validateSignature(
      message: BytesLike,
      signature: BytesLike,
      publicKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    validateSignature(
      message: BytesLike,
      signature: BytesLike,
      publicKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
