/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Metadata,
  MetadataInterface,
} from "../../../contracts/interfaces/Metadata";

const _abi = [
  {
    inputs: [],
    name: "NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VERSION",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Metadata__factory {
  static readonly abi = _abi;
  static createInterface(): MetadataInterface {
    return new utils.Interface(_abi) as MetadataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Metadata {
    return new Contract(address, _abi, signerOrProvider) as Metadata;
  }
}
