/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  EntryPointManager,
  EntryPointManagerInterface,
} from "../../../contracts/core/EntryPointManager";

const _abi = [
  {
    inputs: [],
    name: "CallerNotEntryPoint",
    type: "error",
  },
] as const;

export class EntryPointManager__factory {
  static readonly abi = _abi;
  static createInterface(): EntryPointManagerInterface {
    return new utils.Interface(_abi) as EntryPointManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EntryPointManager {
    return new Contract(address, _abi, signerOrProvider) as EntryPointManager;
  }
}
