/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  RecoveryManager,
  RecoveryManagerInterface,
} from "../../../contracts/core/RecoveryManager";

const _abi = [
  {
    inputs: [],
    name: "CallerNotEntryPoint",
    type: "error",
  },
  {
    inputs: [],
    name: "CallerNotSelf",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "ErrorRecoveror",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "recoveror",
        type: "address",
      },
    ],
    name: "AddedRecoveror",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "recoveror",
        type: "address",
      },
    ],
    name: "RemovedRecoveror",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recoveror",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "addRecoveror",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "start",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "pageSize",
        type: "uint256",
      },
    ],
    name: "getRecoverorsPaginated",
    outputs: [
      {
        internalType: "address[]",
        name: "array",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "next",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recoveror",
        type: "address",
      },
    ],
    name: "isRecoverorEnabled",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "prevRecoveror",
        type: "address",
      },
      {
        internalType: "address",
        name: "recoveror",
        type: "address",
      },
    ],
    name: "removeRecoveror",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class RecoveryManager__factory {
  static readonly abi = _abi;
  static createInterface(): RecoveryManagerInterface {
    return new utils.Interface(_abi) as RecoveryManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RecoveryManager {
    return new Contract(address, _abi, signerOrProvider) as RecoveryManager;
  }
}
