/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Ierc1822Proxiable } from "../Ierc1822Proxiable";

export class Ierc1822Proxiable__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Ierc1822Proxiable {
    return new Contract(address, _abi, signerOrProvider) as Ierc1822Proxiable;
  }
}

const _abi = [
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
